build: fix build system, add current build scripts

diff --git a/bin/release/prerelease b/bin/release/prerelease
--- a/bin/release/prerelease
+++ b/bin/release/prerelease
@@ -1,45 +1,48 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 REQUIRED_TOOLS=(
-  hugo
-  git
-  go
+	git
+	hugo
+	typos
+	curl
 )
 
 for TOOL in "${REQUIRED_TOOLS[@]}"; do
-  if ! command -v "${TOOL}" >/dev/null; then
-    echo "${TOOL} is required... "
-    exit 1
-  fi
+	if ! command -v "${TOOL}" >/dev/null; then
+		echo "${TOOL} is required... "
+		exit 1
+	fi
 done
 
-SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 || exit ; pwd -P )"
+SCRIPTPATH="$(
+	cd "$(dirname "$0")" >/dev/null 2>&1 || exit
+	pwd -P
+)"
+CURPATH="$(pwd -P)"
+
+typos -- ./content
+
+"${CURPATH}"/bin/build/component-tags
 
 if test -f "$SCRIPTPATH"/replacements; then
-  while read -ra __; do
-    go mod edit -dropreplace "${__[0]}"
-  done < "$SCRIPTPATH"/replacements
+	while read -ra __; do
+		go mod edit -dropreplace "${__[0]}"
+	done <"$SCRIPTPATH"/replacements
 fi
+
+#"${CURPATH}"/bin/build/prepare-docs
 
 hugo mod get -u ./...
 hugo mod tidy
 
-git add go.mod --force
-git add go.sum --force
-
-# # just in case: 
-# # if we want to add the fully built static website to the repository 
-# # this would be the place to add this
-# # something like:
-# rm -rf public
-# hugo
-# git add public
-# # no need to commit the site, it will be commited on release
-
-if test -f "$SCRIPTPATH"/replacements; then
-  while read -ra __; do
-    go mod edit -replace "${__[0]}"="${__[1]}"
-  done < "$SCRIPTPATH"/replacements
+git add "${CURPATH}"/go.mod
+FILE="${CURPATH}"/go.sum
+if test -f "$FILE"; then
+	git add go.sum
 fi
 
-echo "Executed in ${SECONDS}s"
+if test -f "$SCRIPTPATH"/replacements; then
+	while read -ra __; do
+		go mod edit -replace "${__[0]}"="${__[1]}"
+	done <"$SCRIPTPATH"/replacements
+fi
